2019-11-19 14:59:28,578 ERROR: Exception on /profile/harsh [GET] [in /usr/local/lib/python3.7/dist-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/harshalgangurde/Workspace/Flask/microblog/app/routes.py", line 73, in profile
    posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/harshalgangurde/Workspace/Flask/microblog/app/templates/profile.html", line 7, in top-level template code
    {% extends "base.html" %}
  File "/home/harshalgangurde/Workspace/Flask/microblog/app/templates/base.html", line 8, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python3.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/usr/local/lib/python3.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/usr/local/lib/python3.7/dist-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/harshalgangurde/Workspace/Flask/microblog/app/templates/base.html", line 45, in block "navbar"
    <li><a href="{{ url_for('user', username=current_user.username) }}">{{ _('Profile') }}</a></li>
  File "/usr/local/lib/python3.7/dist-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/usr/local/lib/python3.7/dist-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'explore' instead?
2019-11-19 14:59:53,448 INFO: Microblog Startup... [in /home/harshalgangurde/Workspace/Flask/microblog/app/__init__.py:37]
2019-11-19 15:02:19,582 INFO: Microblog Startup... [in /home/harshalgangurde/Workspace/Flask/microblog/app/__init__.py:37]
2019-11-19 15:04:52,556 INFO: Microblog Startup... [in /home/harshalgangurde/Workspace/Flask/microblog/app/__init__.py:37]
2019-11-19 15:04:55,929 INFO: Microblog Startup... [in /home/harshalgangurde/Workspace/Flask/microblog/app/__init__.py:37]
2019-11-19 15:06:12,133 INFO: Microblog Startup... [in /home/harshalgangurde/Workspace/Flask/microblog/app/__init__.py:37]
